export const CONFERENCE_IMPORT_UPLOAD_MAX_FILES = 50;
export const CONFERENCE_IMPORT_UPLOAD_MAX_FILE_BYTES = 25 * 1024 * 1024;
export const CONFERENCE_IMPORT_UPLOAD_MAX_BATCH_BYTES = 200 * 1024 * 1024;
export const CONFERENCE_IMPORT_UPLOAD_TEMP_DIRECTORY =
  "/tmp/conference-import-uploads";
