server {
    listen 80;
    server_name localhost;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Ensure ES module workers are served with JavaScript MIME type.
    location ~* \.mjs$ {
        root /usr/share/nginx/html;
        types { application/javascript mjs; }
        default_type application/javascript;
        try_files $uri =404;
    }

    # error_page  404              /404.html;

    # redirect server error pages to the static page /500.x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
