FROM oven/bun:1 AS build

WORKDIR /app

COPY package.json ./
RUN bun install

COPY . .
RUN bun run build

FROM oven/bun:1 AS runtime

WORKDIR /app
ENV NODE_ENV=production

COPY package.json ./
RUN bun install --production

COPY --from=build /app/dist ./dist

EXPOSE 3000
CMD ["bun", "dist/main.js"]
